/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./../src/components/Base/BaseCard.vue')['default']
    BaseFilePicker: typeof import('./../src/components/Base/BaseFilePicker.vue')['default']
    BaseSelect: typeof import('./../src/components/Base/BaseSelect.vue')['default']
    ProgressSection: typeof import('./../src/components/Base/ProgressSection.vue')['default']
    SelectI18n: typeof import('./../src/components/Base/SelectI18n.vue')['default']
  }
}

// For TSX support
declare global {
  const BaseCard: typeof import('./../src/components/Base/BaseCard.vue')['default']
  const BaseFilePicker: typeof import('./../src/components/Base/BaseFilePicker.vue')['default']
  const BaseSelect: typeof import('./../src/components/Base/BaseSelect.vue')['default']
  const ProgressSection: typeof import('./../src/components/Base/ProgressSection.vue')['default']
  const SelectI18n: typeof import('./../src/components/Base/SelectI18n.vue')['default']
}